###
POST http://127.0.0.1:8000/accounts/register/ HTTP/1.1
Content-Type: application/json
 
{
  "email": "testuser@gmail.com",
  "first_name": "User",
  "last_name": "Test",
  "phone_number": "+9779830000000",
  "password": "Test@12345",
  "password2": "Test@12345"
}


###
POST http://127.0.0.1:8001/api/token/ HTTP/1.1
Content-Type: application/json

{
  "email": "customer1@gmail.com",
  "password": "test@9824"
}


###

###
POST http://127.0.0.1:8000/accounts/become-worker/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg4MTI2LCJpYXQiOjE3NzM5ODYzMjYsImp0aSI6IjdlMTk0M2VlOTFjMzQ4YmViYThlMDNkYmI2NmVhM2VhIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.EI24x8yPcsErwkFZPIf5gdSO50sVVqZeNeMC4PtuYew
Content-Type: application/json

{
  "service_category": "Electrician",
  "skills": "Wiring, repair",
  "bio": "3 years experience",
  "hourly_rate": "300.00",
  "service_latitude": "27.7100",
  "service_longitude": "85.3200",
  "service_radius_km": "10.00"
}


### Upload Worker Document
POST http://127.0.0.1:8000/accounts/worker/documents/upload/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg4MTI2LCJpYXQiOjE3NzM5ODYzMjYsImp0aSI6IjdlMTk0M2VlOTFjMzQ4YmViYThlMDNkYmI2NmVhM2VhIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.EI24x8yPcsErwkFZPIf5gdSO50sVVqZeNeMC4PtuYew
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document_type"

Citizenship
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document_number"

CIT-12345
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="document_file"; filename="citizenship.jpg"
Content-Type: image/jpeg

< ./static/citizenship.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

GET http://127.0.0.1:8000/accounts/me/ HTTP/1.1
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg4MTI2LCJpYXQiOjE3NzM5ODYzMjYsImp0aSI6IjdlMTk0M2VlOTFjMzQ4YmViYThlMDNkYmI2NmVhM2VhIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.EI24x8yPcsErwkFZPIf5gdSO50sVVqZeNeMC4PtuYew
###
PATCH http://127.0.0.1:8000/accounts/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg4MDI5LCJpYXQiOjE3NzM5ODYyMjksImp0aSI6IjQxNTZhY2U2MjIyMDQwY2FhMjZiMDRlNTA0NDlkMDllIiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.Ovy3FLZK_sw9uyow0wwgdkzBIQvHkk2v2x5Hh8fHsSE
Content-Type: application/json

{
  "current_latitude": "27.7172",
  "current_longitude": "85.3240",
  "current_address": "Kathmandu",
  "preferred_radius_km": "8.00"
}


###
GET http://127.0.0.1:8000/accounts/worker/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzM4MDQ1LCJpYXQiOjE3NzEzMzYyNDUsImp0aSI6IjRmNzgwN2QyNTNlYjRjNGFhODgxMGY0MzFhMGNlMGRjIiwidXNlcl9pZCI6ImM4NGEzOTI4LTU0NzItNDVkZC1hNzlhLTJhY2I1M2FkODRiZSJ9.-8P9-0hTDdLkEwJL7bDsRqqqXr8LHLiteUx1M3SirY8
###
GET http://127.0.0.1:8000/accounts/worker/documents/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzMyOTkxLCJpYXQiOjE3NzEzMzExOTEsImp0aSI6IjMwMDk0NmEwMjNkNzQ0OWI4ZDkxZWEzMTU0ZTE1YTYwIiwidXNlcl9pZCI6ImI2ZTAyN2MwLTcxZjgtNGE2Ni05NmU5LWQxMzFlODg1NjQ0NSJ9.yEV1rXE-8WgVNyQ4neu1Zu5eJkojHXwQC-5r-1l3PVk

###
PATCH http://127.0.0.1:8000/accounts/worker/profile/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzM4MDQ1LCJpYXQiOjE3NzEzMzYyNDUsImp0aSI6IjRmNzgwN2QyNTNlYjRjNGFhODgxMGY0MzFhMGNlMGRjIiwidXNlcl9pZCI6ImM4NGEzOTI4LTU0NzItNDVkZC1hNzlhLTJhY2I1M2FkODRiZSJ9.-8P9-0hTDdLkEwJL7bDsRqqqXr8LHLiteUx1M3SirY8
Content-Type: application/json

{
  "skills": "Wiring, repair, installation and maintenance",
  "bio": "I have 3 years experience in electrical work.",
  "hourly_rate": "210.00",
  "service_latitude": "27.42092",
  "service_longitude": "85.20471",
  "service_radius_km": "15.00"
}
###
GET http://127.0.0.1:8000/accounts/me/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg5MTQzLCJpYXQiOjE3NzM5ODczNDMsImp0aSI6ImMzZGU4N2MwNDhjNTRjMGNiNGY2ZjU0Y2IxNDRlMzhlIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.gLU0JMVavqwsBcpQxcyjJ1Wm6DJ5sWDkk6y9tF04r9I
###

DELETE http://127.0.0.1:8000/accounts/profile/delete/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzMyOTkxLCJpYXQiOjE3NzEzMzExOTEsImp0aSI6IjMwMDk0NmEwMjNkNzQ0OWI4ZDkxZWEzMTU0ZTE1YTYwIiwidXNlcl9pZCI6ImI2ZTAyN2MwLTcxZjgtNGE2Ni05NmU5LWQxMzFlODg1NjQ0NSJ9.yEV1rXE-8WgVNyQ4neu1Zu5eJkojHXwQC-5r-1l3PVk

###
GET http://127.0.0.1:8000/accounts/worker/profile/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzM1MjEwLCJpYXQiOjE3NzEzMzM0MTAsImp0aSI6Ijc1ZmQ0MDZhNjkyNzQwMjk5NTkzY2M1MjRmNGE5OWIwIiwidXNlcl9pZCI6IjExNGFjNGNhLTUyOWQtNDA2MS1iZmRjLWNhN2M0ODA0YWE1MiJ9.JT5cj6zS-K6ywuNA6RL4ru78ZN70rDB_TPfor16wghA
###
GET http://127.0.0.1:8000/accounts/worker/documents/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzcxMzM4MDQ1LCJpYXQiOjE3NzEzMzYyNDUsImp0aSI6IjRmNzgwN2QyNTNlYjRjNGFhODgxMGY0MzFhMGNlMGRjIiwidXNlcl9pZCI6ImM4NGEzOTI4LTU0NzItNDVkZC1hNzlhLTJhY2I1M2FkODRiZSJ9.-8P9-0hTDdLkEwJL7bDsRqqqXr8LHLiteUx1M3SirY8


###
POST http://127.0.0.1:8000/accounts/admin/workers/a6733b04-3f54-44b6-b9be-8aab17afce2b/verify/

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg5MjYxLCJpYXQiOjE3NzM5ODc0NjEsImp0aSI6ImRmY2NmNzg4ZjAxOTQ2MDhhMDI5ODhkZjdkYzU4MjAyIiwidXNlcl9pZCI6IjA4NzllMmIxLThmYTgtNDYzNS04MjNkLWFhZmU5M2NjYTNmYSJ9.rzIvC8lBPduQC1My11gwPbshWIcgm0Tmr2OMg_QisC0

###
POST http://127.0.0.1:8000/accounts/admin/documents/bcfb8673-2330-4f39-a792-7ef9384c2d6f/verify/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg5NTcxLCJpYXQiOjE3NzM5ODc3NzEsImp0aSI6IjhmZjBkNzAzYTA2NzQ5MmE4MjllNDBmYzE0YjczNDRmIiwidXNlcl9pZCI6IjA4NzllMmIxLThmYTgtNDYzNS04MjNkLWFhZmU5M2NjYTNmYSJ9.Sr-Lpegkq4wptUrbMBiTLECzhYsL0vyF-o2DxvtMSDQ
Content-Type: application/json

{
  "action": "approve"
}

###
POST http://127.0.0.1:8000/accounts/admin/workers/a6733b04-3f54-44b6-b9be-8aab17afce2b/verify/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTg5MjYxLCJpYXQiOjE3NzM5ODc0NjEsImp0aSI6ImRmY2NmNzg4ZjAxOTQ2MDhhMDI5ODhkZjdkYzU4MjAyIiwidXNlcl9pZCI6IjA4NzllMmIxLThmYTgtNDYzNS04MjNkLWFhZmU5M2NjYTNmYSJ9.rzIvC8lBPduQC1My11gwPbshWIcgm0Tmr2OMg_QisC0
Content-Type: application/json

{
  "action": "approve"
}

###
PATCH http://127.0.0.1:8000/accounts/worker/availability/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwMTM0LCJpYXQiOjE3NzM5ODgzMzQsImp0aSI6IjhlNzczN2I4OWQxMzQ4OTE4OWY4ZjgwMDA2ZDAyYWFhIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.-bFdBEojkI_CypvjWPk2CPLrbAd6Vj4xuCTOXuXHPqM
Content-Type: application/json

{
  "availability_status": "Active"
}

###
GET http://127.0.0.1:8000/services/recommended-workers/?service_category=Electrician&radius=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwMTc4LCJpYXQiOjE3NzM5ODgzNzgsImp0aSI6IjhiMjYwNWNkZWFiYjQyZTRhZGE0MTlkNWVhNGY3ZDQzIiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.ltXfXCUAGfjHjLWwdfhsojLVy8tReepZE_KtPCvo_Sg


###
POST http://127.0.0.1:8000/services/requests/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwMTc4LCJpYXQiOjE3NzM5ODgzNzgsImp0aSI6IjhiMjYwNWNkZWFiYjQyZTRhZGE0MTlkNWVhNGY3ZDQzIiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.ltXfXCUAGfjHjLWwdfhsojLVy8tReepZE_KtPCvo_Sg
Content-Type: application/json

{
  "category": "66f64b68-027e-423d-a56f-86f2b698fa51",
  "title": "Need urgent wiring fix",
  "description": "Switchboard issue",
  "request_latitude": "27.7172",
  "request_longitude": "85.3240",
  "request_address": "Kathmandu",
  "search_radius_km": "8.00"
}

###
GET http://127.0.0.1:8000/services/worker/inbox/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NzU2MDUzLCJpYXQiOjE3NzQ3NTQyNTMsImp0aSI6IjE0YzlkZTlmYjQwZjQ5YmE4Y2M4MzIyMjk2ZGNiYjcxIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.d_CmxiTN0L7lLVwARO198nX_2A89dhcIP3u6jQ6PUfU


###
POST http://127.0.0.1:8000/services/worker/inbox/d93676c5-38b5-484d-97de-27f254b515bb/action/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwNDk3LCJpYXQiOjE3NzM5ODg2OTcsImp0aSI6ImUxY2Y1NTA0ZjIwOTRmZDg5OGQ2ZWU1MWQzYzI2MjIzIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.DtTj9SvPfOrGArCvwrxbtiblycn_b_TkItVFit0mXA0
Content-Type: application/json

{
  "action": "accept"
}

###
POST http://127.0.0.1:8000/services/requests/9607f137-56c9-42f6-8a5c-5775733649fb/worker-status/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwNDk3LCJpYXQiOjE3NzM5ODg2OTcsImp0aSI6ImUxY2Y1NTA0ZjIwOTRmZDg5OGQ2ZWU1MWQzYzI2MjIzIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.DtTj9SvPfOrGArCvwrxbtiblycn_b_TkItVFit0mXA0
Content-Type: application/json

{
  "status": "COMPLETED",
  "detail": "Work done"
}

###
POST http://127.0.0.1:8000/ratings/reviews/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwNzMzLCJpYXQiOjE3NzM5ODg5MzMsImp0aSI6IjJjY2I1MTk3ZjQxMDRhYzRhNTcxYjI3Mjk0MGYyYTcyIiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.xCpjY8kEez_-tFtxyIzPA0j_e-QKz5WRopu_DIMzUU0
Content-Type: application/json

{
  "request": "9607f137-56c9-42f6-8a5c-5775733649fb",
  "rating": 5,
  "review_text": "Very professional and fast service"
}
###
GET http://127.0.0.1:8000/ratings/sentiments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkwNzMzLCJpYXQiOjE3NzM5ODg5MzMsImp0aSI6IjJjY2I1MTk3ZjQxMDRhYzRhNTcxYjI3Mjk0MGYyYTcyIiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.xCpjY8kEez_-tFtxyIzPA0j_e-QKz5WRopu_DIMzUU0


###
GET http://127.0.0.1:8000/services/recommended-workers/?service_category=Electrician&radius=8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkxMDMxLCJpYXQiOjE3NzM5ODkyMzEsImp0aSI6IjkyZjM2ZTliNjIyZTRhNmI5NmIzOGJmZDNmOGY2YWE5IiwidXNlcl9pZCI6ImQ1NmFhMThjLTIwODAtNGM4MS04NDc0LTNhMWNlMWMxM2I1NyJ9.yWKC0axmXunhwJV_GAZxe0LVXHqVkiKoJIZaQ_nkJ1s

###
PATCH http://127.0.0.1:8000/accounts/worker/availability/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzczOTkxMTA0LCJpYXQiOjE3NzM5ODkzMDQsImp0aSI6ImEwOGMxOTYzMjAwMDRkMzg5ZjFiZWNmZmIxMmEzMTY2IiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.SfYBz9AWiEVQlINQlw415aWtAaroNwkvWIzKxAssUlI
Content-Type: application/json

{
  "availability_status": "Active"
}


###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
"email": "customer1@gmail.com",
"password": "test@9824"
}

###
POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
"email": "worker1@gmail.com",
"password": "test@9824"
}

POST http://127.0.0.1:8000/services/worker/inbox/{broadcast_id}/action/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NzU2MDUzLCJpYXQiOjE3NzQ3NTQyNTMsImp0aSI6IjE0YzlkZTlmYjQwZjQ5YmE4Y2M4MzIyMjk2ZGNiYjcxIiwidXNlcl9pZCI6ImE2NzMzYjA0LTNmNTQtNDRiNi1iOWJlLThhYWIxN2FmY2UyYiJ9.d_CmxiTN0L7lLVwARO198nX_2A89dhcIP3u6jQ6PUfU
Content-Type: application/json

{
"action": "accept"
}
